### ISSUE TITLE
pylru can't be uninstalled by pip

### ISSUE THREAD

**Issue by cabiad** [jlhutch/pylru#11] opened 2015-03-13 22:20 UTC
```
$ virtualenv .
Running virtualenv with interpreter /usr/bin/python2
New python executable in ./bin/python2
Also creating executable in ./bin/python
Installing setuptools, pip...done.
$ bin/pip install pylru
Downloading/unpacking pylru
  Downloading pylru-1.0.6.tar.gz
  Running setup.py (path:/home/chris/play/build/pylru/setup.py) egg_info for package pylru
    
Installing collected packages: pylru
  Running setup.py install for pylru
    
Successfully installed pylru
Cleaning up...
$ bin/pip uninstall pylru
Can't uninstall 'pylru'. No files were found to uninstall.
$ bin/pip freeze
argparse==1.2.1
pylru==1.0.6
wsgiref==0.1.2
```

**Comment by jlhutch** [comment] 2015-03-16 18:38
Looking at the setup script, I don't see what is causing this. Does anyone else have an idea?

**Comment by brechtm** [comment] 2015-03-26 10:11
No problem uninstalling from a virtual env:

    $ pip uninstall pylru
    Uninstalling pylru-1.0.9:
      /Users/brechtm/Documents/Code/virtualenvs/science/lib/python2.7/site-packages/pylru-1.0.9-py2.7.egg-info
      /Users/brechtm/Documents/Code/virtualenvs/science/lib/python2.7/site-packages/pylru.py
      /Users/brechtm/Documents/Code/virtualenvs/science/lib/python2.7/site-packages/pylru.pyc
    Proceed (y/n)? y
      Successfully uninstalled pylru-1.0.9

**Comment by jlhutch** [comment] 2015-03-28 04:33
I have been unable to reproduce the problem as well and am closing the issue.

**Closed by jlhutch** 2015-03-28 04:33 UTC
